# Subscriptions

## List
GET http://127.0.0.1:8081/subscription

## Add
POST http://127.0.0.1:8081/subscription
Content-Type: application/json

[
  {"url": "http://example.net/feed.rss", "title": "Example Feed 1"},
  {"url": "http://example.org/feed.rdf", "title": "Example Feed 2"}
]

## Remove
DELETE http://127.0.0.1:8081/subscription
Content-Type: application/json

[
  "http://example.net/feed.rss",
  2,
  "http://invalid.example.com"
]

#
