# Subscriptions

## List
GET http://127.0.0.1:8081/subscription

## Add
POST http://127.0.0.1:8081/subscription
Content-Type: application/json

[
  {"url": "http://example.net/feed.rss", "title": "Example Feed 1"},
  {"url": "http://example.org/feed.rdf", "title": "Example Feed 2"}
]

## Update
PUT http://127.0.0.1:8081/subscription
Content-Type: application/json

[
  {"userId": 1, "feedId": 1, "title": "Updated Subscription Title 1"},
  {"userId": 1, "feedId": 2, "title": "Updated Subscription Title 2"}
]

## Remove
DELETE http://127.0.0.1:8081/subscription
Content-Type: application/json

[
  "http://example.net/feed.rss",
  2,
  "http://invalid.example.com"
]

# Feeds
## List
GET http://127.0.0.1:8081/feed

## Add
POST http://127.0.0.1:8081/feed
Content-Type: application/json

[
  {"url": "http://example.net/feed1.rss", "title": "Title for Feed 1"},
  {"url": "http://example.org/feed2.rdf", "title": "Title for Feed 2"}
]

## Update
PUT http://127.0.0.1:8081/feed
Content-type: application/json

[
  {"id": 1, "title": "Title for First Feed"},
  {"id": 2, "title": "Title for Second Feed"}
]

## Remove
DELETE http://127.0.0.1:8081/feed
Content-Type: application/json

[
  "http://example.net/feed.rss",
  2
]
